-- SQL Class Excercise - Home Tools Inc. 
-- Joe Lee 

--1 
SELECT * FROM VENDOR; 

SELECT ALL * FROM VENDOR; 

--2 
SELECT V_CODE, V_NAME, V_STATE
FROM VENDOR; 

--3 
SELECT * FROM PRODUCT; 

--4 
SELECT P_CODE 'PPRODUCT CODE', P_DESCRIPT AS 'PRODUCT NAME'
FROM PRODUCT; 

--5 
SELECT V_STATE 
FROM VENDOR; 

--6 
SELECT DISTINCT V_STATE
FROM VENDOR; 

--7 
SELECT * FROM PRODUCT 
WHERE P_PRICE > = 40; 

--8
SELECT * FROM PRODUCT 
WHERE P_CODE = 'WR3/TT3'; 

--9
SELECT * FROM VENDOR 
WHERE V_STATE = 'GA'; 

--10 
SELECT * FROM PRODUCT 
WHERE P_QOH < = 10 
AND P_PRICE > 50; 

--11 
SELECT * FROM PRODUCT 
WHERE P_QOH > = P_MIN 
AND P_PRICE > 200; 

--12 
SELECT * FROM VENDOR 
WHERE V_STATE = 'KY' 
OR V_STATE = 'GA';

--13
SELECT * FROM PRODUCT 
WHERE (V_CODE = 21344 
OR V_CODE = 24288)
AND P_PRICE > 15; 

--13 (Can also be written) 
SELECT * FROM PRODUCT 
WHERE V_CODE IN (21344, 24288)
AND P_PRICE > 15; 

--14 
SELECT * FROM PRODUCT 
WHERE V_CODE = 21344 
ORDER BY P_PRICE ASC; 

--15
SELECT * FROM PRODUCT 
WHERE P_INDATE > '2006-1-1' 
ORDER BY V_CODE ASC, P_PRICE DESC; 

--16
SELECT * FROM PRODUCT 
WHERE V_CODE = 25595 
OR V_CODE = 21344 
OR V_CODE = 24288 
ORDER BY V_CODE; 

--17 
SELECT * FROM PRODUCT 
WHERE P_PRICE BETWEEN 30 AND 50; 

--18 
SELECT * FROM PRODUCT 
WHERE P_PRICE < 5 
OR P_PRICE > 200; 

--19 
SELECT * FROM VENDOR 
WHERE V_NAME LIKE 'Br%';

--20 
SELECT * FROM PRODUCT 
WHERE V_CODE LIKE '212__'; 

--21 
SELECT * FROM VENDOR 
WHERE V_AREACODE LIKE '9__'; 

--22 
SELECT COUNT(DISTINCT V_AREACODE) 
FROM VENDOR; 

--25 
SELECT V_CODE, COUNT(*) AS 'PRODUCT COUNT', AVG(P_PRICE) AS 'AVERAGE PRICE' 
FROM PRODUCT 
WHERE V_CODE IS NOT NULL 
GROUP BY V_CODE 
ORDER BY V_CODE ASC; 

--29 
SELECT V_CODE, COUNT(*) AS 'PRODUCT COUNT', SUM(P_QOH * P_PRICE) AS 'INVENTORY VALUE'
FROM PRODUCT 
WHERE V_CODE IS NOT NULL 
GROUP BY V_CODE 
ORDER BY 3 ASC; 

--31 (Can also be written for # 29)  
SELECT V_CODE, COUNT(*) AS 'PRODUCT COUNT', SUM(P_QOH * P_PRICE) AS 'INVENTORY VALUE'
FROM PRODUCT 
WHERE V_CODE IS NOT NULL 
GROUP BY V_CODE 
HAVING SUM(P_QOH * P_PRICE) > 2000 
ORDER BY 'INVENTORY VALUE' ASC; 








