--SQL CLASS EXCERCISE # 4 
-- Joe Lee 

--1 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
UNION 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER_2 

--2 
SELECT V_NAME, V_AREACODE, V_PHONE 
FROM VENDOR 
UNION 
SELECT CUS_LNAME, CUS_AREACODE, CUS_PHONE  
FROM CUSTOMER 

--3 
SELECT CUS_LNAME, CUS_AREACODE 
FROM CUSTOMER 
UNION 
SELECT EMP_LNAME, EMP_AREACODE 
FROM EMPLOYEE 

--4 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
WHERE CUS_AREACODE = 615 
UNION 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
WHERE CUS_AREACODE = 713; 

SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
WHERE CUS_AREACODE = 615 
OR CUS_AREACODE = 713; 

--5 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
UNION ALL 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER_2 

--6 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
INTERSECT  
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER_2 

--7 
SELECT CUS_CODE
FROM CUSTOMER 
WHERE CUS_AREACODE = 615 
INTERSECT 
SELECT DISTINCT CUS_CODE 
FROM INVOICE 

SELECT DISTINCT C.CUS_CODE 
FROM CUSTOMER AS C INNER JOIN INVOICE AS I 
ON C.CUS_CODE = I.CUS_CODE 
WHERE CUS_AREACODE = 615; 

--8 
SELECT DISTINCT CUS_AREACODE 
FROM CUSTOMER 
INTERSECT 
SELECT DISTINCT EMP_AREACODE 
FROM EMPLOYEE; 

--9 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER 
EXCEPT 
SELECT CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_AREACODE 
FROM CUSTOMER_2; 

--10 
SELECT DISTINCT CUS_AREACODE 
FROM CUSTOMER 
EXCEPT 
SELECT EMP_AREACODE 
FROM EMPLOYEE; 

--11 
SELECT * FROM INVOICE CROSS JOIN LINE;

SELECT * FROM INVOICE, LINE; 

--12 
CREATE VIEW CUSTOMERAREACODE615 AS 
SELECT * FROM CUSTOMER 
WHERE CUS_AREACODE = '615' 
SELECT * FROM CUSTOMERAREACODE615; 

--12A 
BEGIN TRANSACTION 
INSERT INTO CUSTOMERAREACODE615 
VALUES(10020, 'Lee', 'Joe', 'J', 615, '243-0910', 202); 

--12E 
ROLLBACK; 

--13 
CREATE VIEW VENDOR_PRODUCT AS 
SELECT V_CODE AS 'VENDOR CODE', COUNT(*) AS 'PRODUCT COUNT', AVG(P_PRICE) AS 'AVERAGE PRICE' 
FROM PRODUCT
WHERE V_CODE IS NOT NULL 
GROUP BY V_CODE 

SELECT * FROM VENDOR_PRODUCT 

--14 
CREATE VIEW NON_INVOICED_PRODUCTS AS 
SELECT P_CODE AS 'PRODUCT CODE', P_DESCRIPT AS 'PRODUCT DESCRIPTION', P_QOH AS 'PRODUCT QUANTITY', P_PRICE AS 'PRODUCT PRICE', P_QOH * P_PRICE AS 'INVENTORY AMOUNT' 
FROM PRODUCT 
WHERE P_CODE NOT IN 
	(SELECT DISTINCT P_CODE 
	FROM LINE); 

SELECT * FROM NON_INVOICED_PRODUCTS 

--15 
CREATE INDEX EMP_DOBX ON EMPLOYEE (EMP_DOB); 

--16 
DROP INDEX EMPLOYEE.EMP_DOBX; 

--17 
SELECT * INTO PRODUCT_BACKUP FROM PRODUCT; 

--18 
SELECT * FROM PRODUCT_BACKUP 

--19 
DROP TABLE PRODUCT_BACKUP; 

--20 
SELECT INV_NUMBER, INV_DATE, I.CUS_CODE, CUS_LNAME, CUS_FNAME 
FROM INVOICE AS I INNER JOIN
	(SELECT CUS_CODE, CUS_LNAME, CUS_FNAME 
	FROM CUSTOMER 
	UNION 
	SELECT CUS_CODE, CUS_LNAME, CUS_FNAME 
	FROM CUSTOMER_2) AS C 
ON I.CUS_CODE = C.CUS_CODE 
ORDER BY INV_NUMBER; 

-- 21 
SELECT * FROM CUSTOMER 
WHERE CUS_CODE IN 
(SELECT CUS_CODE 
FROM CUSTOMER 
WHERE CUS_AREACODE = '615' 
INTERSECT 
SELECT DISTINCT CUS_CODE 
FROM INVOICE)  
ORDER BY 1 DESC; 

--22 
SELECT * FROM VENDOR 
WHERE V_CODE IN 
	(SELECT V_CODE 
	FROM VENDOR 
	EXCEPT
	SELECT DISTINCT V_CODE 
	FROM PRODUCT); 

SELECT * FROM VENDOR 
WHERE V_CODE NOT IN 
	(SELECT V_CODE 
	FROM VENDOR 
	INTERSECT 
	SELECT DISTINCT V_CODE 
	FROM PRODUCT); 
